/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/run_hedgehog_run.glb 
Author: polish_farmer/ Eryk Stańko (https://sketchfab.com/polish_farmer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/run-hedgehog-run-3c8813e9937a48caa1543eba94c307c5
Title: RUN! HEDGEHOG RUN!
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/run_hedgehog_run.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="animation_NEW_ONLY_ONE_ACTION_2fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="Group10031_002_Group10031_003" position={[0.058, 0.366, 7.443]} rotation={[-Math.PI / 2, 0, 0]} scale={0.711} />
                  <group name="Group10031_002_Group10031_000" position={[-23.109, 0.392, -5.708]} scale={0.711} />
                  <group name="robot_RIG" scale={0.802} />
                  <group name="BASE" rotation={[-Math.PI / 2, 0, 0]} scale={10}>
                    <mesh name="BASE_hedgehog_logo_0" geometry={nodes.BASE_hedgehog_logo_0.geometry} material={materials.hedgehog_logo} />
                    <mesh name="BASE_TUBE_0" geometry={nodes.BASE_TUBE_0.geometry} material={materials.TUBE} />
                    <mesh name="BASE_transparent_0" geometry={nodes.BASE_transparent_0.geometry} material={materials.transparent} />
                    <mesh name="BASE_drop_0" geometry={nodes.BASE_drop_0.geometry} material={materials.drop} />
                    <mesh name="BASE_BASE_0" geometry={nodes.BASE_BASE_0.geometry} material={materials.BASE} />
                  </group>
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" position={[326.667, 118.691, -121.852]} rotation={[-Math.PI / 2, 0, 0.507]} scale={10} />
                  <group name="Object_9" position={[20.721, 0, -7.624]} rotation={[-Math.PI / 2, 0, 0.535]} scale={10} />
                  <group name="Object_11" rotation={[-Math.PI / 2, 0, -1.002]} scale={10} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.spark} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.rocket} skeleton={nodes.Object_8.skeleton} />
                  <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.hedgehog} skeleton={nodes.Object_10.skeleton} />
                  <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.robot} skeleton={nodes.Object_12.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/run_hedgehog_run.glb')
