/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/composition_of_frames_for_wall_decoration.glb -o src/components/HeroModels/composition_of_frames_for_wall_decoration.jsx 
Author: 3D Render Box (https://sketchfab.com/3DRenderBox)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/composition-of-frames-for-wall-decoration-f1cdbd8d711b43e58c5edba6caa7b412
Title: Composition of frames for wall decoration
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/composition_of_frames_for_wall_decoration.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Material2.geometry} material={materials.Gold_14k} />
        <lineSegments geometry={nodes.Material4.geometry} material={materials.edge_color247200141255} />
        <mesh geometry={nodes.Material2_1.geometry} material={materials['13010_2']} />
        <lineSegments geometry={nodes.Material3.geometry} material={materials.edge_color225227223255} />
        <lineSegments geometry={nodes.Material3_1.geometry} material={materials.edge_color116116116255} />
        <mesh geometry={nodes.Material2_2.geometry} material={materials['13580_2']} />
        <lineSegments geometry={nodes.Material3_2.geometry} material={materials.edge_color251251251255} />
        <mesh geometry={nodes.Material2_3.geometry} material={materials['11648_2']} />
        <lineSegments geometry={nodes.Material3_3.geometry} material={materials.edge_color000255} />
        <mesh geometry={nodes.Material2_4.geometry} material={materials['3393_2']} />
        <lineSegments geometry={nodes.Material3_4.geometry} material={materials.edge_color190199191255} />
        <mesh geometry={nodes.Material2_5.geometry} material={materials.Papier_blanc} />
        <mesh geometry={nodes.Material2_6.geometry} material={materials.Glass} />
        <lineSegments geometry={nodes.Material3_5.geometry} material={materials.edge_color00037} />
        <lineSegments geometry={nodes.Material3_6.geometry} material={materials.edge_color162162162255} />
        <mesh geometry={nodes.Material2_7.geometry} material={materials['11532_2']} />
        <lineSegments geometry={nodes.Material3_7.geometry} material={materials.edge_color231231231255} />
        <mesh geometry={nodes.Material2_8.geometry} material={materials['8191_2']} />
        <mesh geometry={nodes.Material3_8.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/composition_of_frames_for_wall_decoration.glb')
