/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gaming_desktop_pc.glb
Author: Yolala1232 (https://sketchfab.com/Yolala1232)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-desktop-pc-d1d8282c9916438091f11aeb28787b66
Title: Gaming Desktop PC
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function GamingDesktop({ screenImage, ...props }) {
  const groupRef = useRef();
  const { scene, nodes, materials } = useGLTF('/models/gaming_desktop_pc.glb');
  
  const defaultImage = screenImage || '/images/music.jpg';

  useEffect(() => {
    console.log('🖥️ Loading screen image into Gaming Desktop PC...');
    
    const texture = new THREE.TextureLoader().load(
      defaultImage,
      () => console.log('✅ Screen image loaded'),
      undefined,
      (err) => console.error('❌ Failed to load screen image:', err)
    );
    
    // Make texture look nice
    texture.wrapS = THREE.RepeatWrapping;
    texture.wrapT = THREE.RepeatWrapping;
    
    // Find the screen mesh
    let screenFound = false;
    
    scene.traverse((child) => {
      if (child.isMesh) {
        // Look for mesh names that might be the screen
        const isScreen = 
          child.name?.includes('OnTheFly') ||      // Object_782_OnTheFly-bg_0
          child.name?.includes('MY_SCREEN') ||     // MY_SCREEN_MY_SCREEN_0
          child.name?.toLowerCase().includes('screen') ||
          child.name?.toLowerCase().includes('monitor') ||
          child.name?.toLowerCase().includes('display');
        
        if (isScreen && !screenFound) {
          child.material = new THREE.MeshStandardMaterial({
            map: texture,
            color: '#9f0101',
            roughness: 0.2,
            metalness: 0.1,
            emissive: '#d82408',
            emissiveIntensity: 0.2
          });
          console.log(`📺 Applied image to screen: ${child.name}`);
          screenFound = true;
        }
      }
    });
    
    if (!screenFound) {
      console.warn('⚠️ Screen mesh not found. Trying first mesh...');
      // Fallback: apply to the first mesh we find
      scene.traverse((child) => {
        if (child.isMesh && !screenFound) {
          child.material = new THREE.MeshStandardMaterial({
            map: texture,
            color: '#e00a0a',
            roughness: 0.2,
            metalness: 0.1
          });
          console.log(`📺 Applied image to fallback mesh: ${child.name}`);
          screenFound = true;
        }
      });
    }
  }, [scene, defaultImage]);

  // Note: The model has a scale of 0.01 in the original file
  // We'll let the parent handle scaling
  return <primitive ref={groupRef} object={scene} {...props} />;
}

useGLTF.preload('/models/gaming_desktop_pc.glb');