/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/picture_frame_collection.glb
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picture-frame-collection-987f8659bdd34549955c38ea1f4a6fe9
Title: Picture frame collection
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function PictureFrameCollection({ images, ...props }) {
  const groupRef = useRef();
  const { scene, nodes, materials } = useGLTF('/models/picture_frame_collection.glb');
  
  // Your images - one for each frame (at least 7 frames in this model)
  const defaultImages = images || [
    '/images/photo1.jpg',
    '/images/photo2.jpg',
    '/images/photo3.jpg',
    '/images/photo4.jpg',
    '/images/photo5.jpg',
    '/images/photo6.jpg',
    '/images/photo7.jpg'
  ];

  useEffect(() => {
    console.log('🎨 Loading images into picture frames...');
    
    // Create textures
    const textures = defaultImages.map((url, index) => {
      const texture = new THREE.TextureLoader().load(
        url,
        () => console.log(`✅ Image ${index + 1} loaded`),
        undefined,
        (err) => console.error(`❌ Failed: ${url}`, err)
      );
      return texture;
    });

    // Find all meshes with "T_frame_and_pictures" material
    // These are the picture surfaces
    let pictureIndex = 0;
    
    scene.traverse((child) => {
      if (child.isMesh && pictureIndex < textures.length) {
        // Check if this mesh is a picture surface
        const isPictureSurface = 
          child.material?.name === 'T_frame_and_pictures' ||
          child.name?.includes('Object_4') ||
          child.name?.includes('Object_8') ||
          child.name?.includes('Object_16') ||
          child.name?.includes('Object_24');
        
        if (isPictureSurface) {
          child.material = new THREE.MeshStandardMaterial({
            map: textures[pictureIndex],
            color: '#ffffff',
            roughness: 0.3,
            metalness: 0.1,
            side: THREE.DoubleSide
          });
          console.log(`📷 Applied image ${pictureIndex + 1} to frame: ${child.name}`);
          pictureIndex++;
        }
      }
    });
    
    console.log(`✅ Applied ${pictureIndex} images to frames`);
  }, [scene, defaultImages]);

  return <primitive ref={groupRef} object={scene} {...props} />;
}

useGLTF.preload('/models/picture_frame_collection.glb');