/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/picture_frame_collection.glb -o src/components/HeroModels/picture_frame_collection.jsx 
Author: Sousinho (https://sketchfab.com/sousinho)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picture-frame-collection-987f8659bdd34549955c38ea1f4a6fe9
Title: Picture frame collection
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/picture_frame_collection.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.T_frame_and_pictures} position={[-2.196, -0.001, 0.001]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.T_frame} position={[-2.196, -0.001, -1.698]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.T_frame_and_pictures} position={[1.168, 0.001, -0.009]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.T_glass_cracked} position={[1.168, 0.001, 0.01]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.T_frame} position={[1.168, 0.001, -1.709]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.T_glass} position={[1.168, 0.001, -1.689]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.T_frame_and_pictures} position={[0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.T_glass_cracked} position={[0.001, 0, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.T_frame} position={[0.001, 0, -1.7]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.T_glass} position={[0.001, 0, -1.7]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.T_frame_and_pictures} position={[-0.976, 0, -0.018]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.T_glass_cracked} position={[-0.976, 0, 0.014]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.T_frame} position={[-0.976, 0, -1.718]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.T_glass} position={[-0.976, 0, -1.685]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/picture_frame_collection.glb')
