/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/composition_of_frames_for_wall_decoration.glb
Author: 3D Render Box (https://sketchfab.com/3DRenderBox)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/composition-of-frames-for-wall-decoration-f1cdbd8d711b43e58c5edba6caa7b412
Title: Composition of frames for wall decoration
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function WallFrames({ images, ...props }) {
  const groupRef = useRef();
  const { scene, nodes, materials } = useGLTF('/models/composition_of_frames_for_wall_decoration.glb');
  
  // Your 5 images
  const defaultImages = images || [
    '/images/music.jpg',
    '/images/music.jpg',
    '/images/music.jpg',
    '/images/music.jpg',
    '/images/music.jpg'
  ];

  useEffect(() => {
    console.log('🎨 Loading images into wall frames...');
    
    // Create textures
    const textures = defaultImages.map((url, index) => {
      const texture = new THREE.TextureLoader().load(
        url,
        () => console.log(`✅ Image ${index + 1} loaded`),
        undefined,
        (err) => console.error(`❌ Failed: ${url}`, err)
      );
      return texture;
    });

    // Method 1: Find all meshes with "Papier_blanc" material
    // These are the picture surfaces
    let pictureIndex = 0;
    
    // Look for all meshes that are picture surfaces
    const pictureMeshNames = [
      'Material2_5',  // This is Papier_blanc - the picture area
      // The model might have multiple picture surfaces with different names
    ];
    
    // Try to find all meshes with "Papier_blanc" material first
    scene.traverse((child) => {
      if (child.isMesh && child.material?.name === 'Papier_blanc' && pictureIndex < textures.length) {
        child.material = new THREE.MeshStandardMaterial({
          map: textures[pictureIndex],
          color: '#ffffff',
          roughness: 0.3,
          metalness: 0.1,
          side: THREE.DoubleSide
        });
        console.log(`📷 Applied image ${pictureIndex + 1} to Papier_blanc mesh`);
        pictureIndex++;
      }
    });
    
    // If we still need more images, look for other potential picture surfaces
    if (pictureIndex < textures.length) {
      scene.traverse((child) => {
        if (child.isMesh && pictureIndex < textures.length) {
          // Check if this mesh might be a picture surface
          const isPotentialPicture = 
            child.name?.includes('Material2') ||
            child.name?.includes('plane') ||
            child.name?.toLowerCase().includes('picture');
          
          if (isPotentialPicture && child.material?.name !== 'Papier_blanc') {
            child.material = new THREE.MeshStandardMaterial({
              map: textures[pictureIndex],
              color: '#ffffff',
              roughness: 0.3,
              metalness: 0.1,
              side: THREE.DoubleSide
            });
            console.log(`📷 Applied image ${pictureIndex + 1} to ${child.name}`);
            pictureIndex++;
          }
        }
      });
    }
    
    console.log(`✅ Applied ${pictureIndex} images to frames`);
  }, [scene, defaultImages]);

  return <primitive ref={groupRef} object={scene} {...props} />;
}

useGLTF.preload('/models/composition_of_frames_for_wall_decoration.glb');